### ISSUE TITLE
Minimum Features?

### ISSUE THREAD

**Issue by shmishtopher** [AndersonRobotics/Uplink#1]
- [ ] WASD driver controls
- [ ] Individual pin controls
- [ ] Command testing
- [ ] Deployment utilities

What features do y'all think we should include. 
@Samcfuchs 
@MichaelBenvenuto 
@sparklypig 
@riverpup525

**Comment by Samcfuchs** [comment]
It seems to me we should be coming at this from the other direction - what are we actually building, and what features do we need to make that possible?

**Comment by shmishtopher** [comment]
Ideally we would have a standard specification for robot communication, I think that would greatly simplify robot development.  Right now each of the demo robots use a different protocol and require their own controllers.  With a standard we could develop a universal driver station.  So I think we should start drafting out  the communication spec.
